spring:
  banner:
    location: "banner.txt"

socket-svr:
  port: 8842
  ssl-port: 8843
  ip: "0.0.0.0"
  security:
    certs-folder: "./certs"
    cert-chain-file: "server.crt"
    private-key-file: "server.key"