spring:
  main:
    allow-circular-references: true
  banner:
    location: "banner.txt"

socket-svr:
  port: 8842
  ip: "0.0.0.0"
  enable-ssl: false
  ssl-port: 8843
  certs-folder: "./certs"
  cert-chain-file: "server.crt"
  private-key-file: "server.key"

log:
  path: log
  prefix: ltsig
  format: "[%date{yyyy-MM-dd HH:mm:ss.SSS}][%thread][%level][%logger{0}] %msg%n"
  reserve-days: 30
  level: INFO