jdbc:
  url: jdbc:sqlite:/path/to/sqlite.db
  driver-class-name: org.sqlite.JDBC

server-address:
  relays:
    - "relay:111.111.111.111:1234:user1:passwd1"
  reflexes:
    - "stun:stun.l.google.com:19302"
    - "stun:stun2.l.google.com:19302"
    - "stun:stun3.l.google.com:19302"

mybatis:
  mapper-locations: classpath:mybatis/mapper/*Mapper.xml
  type-aliases-package: cn.lanthing.svr.entity

log:
  path: log
  prefix: ltsvr
  format: "[%date{yyyy-MM-dd HH:mm:ss.SSS}][%thread][%level][%logger{0}] %msg%n"
  reserve-days: 30
  level: INFO

controlled-socket-svr:
  port: 4567
  ssl-port: 5678
  ip: "0.0.0.0"
  enable-ssl: false
  certs-folder: "./certs"
  cert-chain-file: "server.crt"
  private-key-file: "server.key"

controlling-socket-svr:
  port: 9876
  ssl-port: 8765
  ip: "0.0.0.0"
  enable-ssl: false
  certs-folder: "./certs"
  cert-chain-file: "server.crt"
  private-key-file: "server.key"


signaling:
  ip: "127.0.0.1"
  port: 8842

version:
  file: "/path/to/versions.json"